# Generated by Django 3.2 on 2025-06-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OzonAuthKey',
            fields=[
                ('domain', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('is_disabled', models.BooleanField(default=False, help_text='Выключение домена')),
                ('enable_posting', models.BooleanField(default=True, help_text='Постинг товаров')),
                ('full_update_allowed', models.BooleanField(default=False, help_text='Апдейт цен, остатков и карточек')),
                ('enable_daily_offers_update', models.BooleanField(default=False, help_text='Дополнительное ежедневное обновление карточек')),
                ('logs', models.TextField(blank=True, editable=False, null=True)),
                ('mapping_from_domain', models.ForeignKey(blank=True, help_text='Домен, маппинг которого будет использоваться для постинга', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon.ozonauthkey')),
            ],
            options={
                'verbose_name_plural': 'Domains & API keys',
            },
        ),
        migrations.CreateModel(
            name='OzonFeedUrl',
            fields=[
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ozon.ozonauthkey')),
                ('url', models.TextField()),
                ('parsed', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('collection_name', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('error', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('last_parsed_date', models.DateTimeField(blank=True, help_text='Last date of successful feed parse', null=True)),
                ('parsed_hash', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feed URLs',
            },
        ),
        migrations.CreateModel(
            name='OzonOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_offer_id', models.CharField(db_index=True, max_length=50)),
                ('state', models.CharField(choices=[('processing', 'processing'), ('moderating', 'moderating'), ('processed', 'processed'), ('failed_moderation', 'failed_moderation'), ('failed_validation', 'failed_validation'), ('failed', 'failed')], max_length=30)),
                ('last_import_request_data', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('last_import_hash', models.TextField(blank=True, editable=False, null=True)),
                ('product_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('task_id', models.BigIntegerField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('last_offer_update', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.ozonauthkey')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'unique_together': {('domain', 'feed_offer_id')},
            },
        ),
    ]
